version: '3.8'

services:
    xilinx-2020.2:
        container_name: xilinx-2020.2
        image: ${USER}/xilinx-2020.2
        build:
            context: build_context
            dockerfile: Dockerfile
            args:
                USER: "${USER}"
                UID: "${UID}"
                GID: "${GID}"
                XILINXMAIL: "${XILINXMAIL}"
                XILINXLOGIN: "${XILINXLOGIN}"
        user: "${UID}:${GID}"    ## docker run --user=$USER
        stdin_open: true         ## docker run -i
        tty: true                ## docker run -t
        ## allow privileged for vivado, since we're containering
        ## a build environment mainly for reproducability and we
        ## know what we're doing (hopefully)
        privileged: true
        environment:
          - USER
          - DISPLAY=$DISPLAY
        env_file:
          - .env
        volumes:
          ## folders not need to be around
          - /tmp/.X11-unix:/tmp/.X11-unix
          - ~/.Xauthority:/home/${USER}/.Xauthority:ro
          - ~/.gitconfig:/home/${USER}/.gitconfig:ro
          - ~/.ssh:/home/${USER}/.ssh
          - ./workspace:/home/${USER}/workspace
          ## folder must be around
          - type: bind
            source: ./build_configs
            target: /home/$USER/configs
        network_mode: "host"

